import { describe, expect, it } from "vitest";
import { CATEGORY_KEYWORDS } from "../src/keywords.ts";

/**
 * Block 3 structural tests for `keywords.ts` (kb.md "Categorías
 * Predefinidas" and "Categorización Automática", mitigation R-04).
 */

describe("CATEGORY_KEYWORDS", () => {
  it("has exactly kb.md's normative category order (mitigation R-04)", () => {
    // No AC of the PRD pins this: between AC-05 and AC-15 there are 8
    // category-order boundaries left unfixed, and a silent transposition
    // would pass every AC in green. This test is the only thing anchoring
    // the order to kb.md literally.
    expect(CATEGORY_KEYWORDS.map((entry) => entry.category)).toEqual([
      "Comida",
      "Transporte",
      "Entretenimiento",
      "Servicios",
      "Salud",
      "Alquiler",
      "Indumentaria",
      "Hogar",
      "Cuidado personal",
      "Mascotas",
    ]);
  });

  it("totals exactly 258 keywords across all categories (kb.md:421)", () => {
    const total = CATEGORY_KEYWORDS.reduce(
      (sum, entry) => sum + entry.keywords.length,
      0,
    );
    expect(total).toBe(258);
  });

  it("matches the per-category count documented in kb.md", () => {
    const expectedCounts: Record<string, number> = {
      Comida: 66,
      Transporte: 35,
      Entretenimiento: 28,
      Servicios: 23,
      Salud: 42,
      Alquiler: 4,
      Indumentaria: 14,
      Hogar: 21,
      "Cuidado personal": 16,
      Mascotas: 9,
    };

    for (const entry of CATEGORY_KEYWORDS) {
      expect(entry.keywords.length).toBe(expectedCounts[entry.category]);
    }
  });

  it("matches kb.md's literal keyword content per category (mitigation R-04)", () => {
    // Second, independent transcription of kb.md:373-419, keyword by
    // keyword -- NOT generated from `keywords.ts`. Counts and category
    // order alone cannot catch a keyword swapped between two categories,
    // a keyword mutated to a different (even similarly-counted) string, or
    // an intra-category transposition. This anchors CONTENT, not just
    // shape. Reordering this list to "match" a future keywords.ts edit
    // defeats its purpose -- it must only ever be edited to follow kb.md.
    expect(CATEGORY_KEYWORDS).toEqual([
      {
        category: "Comida",
        keywords: [
          "supermercado",
          "super",
          "almacén",
          "restaurante",
          "delivery",
          "kiosco",
          "verdulería",
          "panadería",
          "desayuno",
          "almuerzo",
          "merienda",
          "cena",
          "vianda",
          "picada",
          "café",
          "cafetería",
          "milanesa",
          "empanada",
          "pizza",
          "hamburguesa",
          "asado",
          "choripán",
          "pancho",
          "sándwich",
          "sanguche",
          "sushi",
          "tarta",
          "ensalada",
          "medialuna",
          "pan",
          "helado",
          "alfajor",
          "galletita",
          "chocolate",
          "yerba",
          "gaseosa",
          "fiambre",
          "queso",
          "leche",
          "huevo",
          "carne",
          "pollo",
          "pescado",
          "verdura",
          "fruta",
          "fideo",
          "arroz",
          "rotisería",
          "carnicería",
          "pescadería",
          "fiambrería",
          "heladería",
          "pizzería",
          "parrilla",
          "dietética",
          "comedor",
          "mayorista",
          "chino",
          "rappi",
          "pedidosya",
          "mcdonalds",
          "coto",
          "carrefour",
          "jumbo",
          "changomas",
          "makro",
        ],
      },
      {
        category: "Transporte",
        keywords: [
          "nafta",
          "combustible",
          "colectivo",
          "subte",
          "tren",
          "taxi",
          "remis",
          "uber",
          "cabify",
          "peaje",
          "estacionamiento",
          "gnc",
          "gasoil",
          "ypf",
          "shell",
          "axion",
          "bondi",
          "sube",
          "micro",
          "combi",
          "pasaje",
          "boleto",
          "didi",
          "cochera",
          "garaje",
          "gomería",
          "lavadero",
          "mecánico",
          "taller",
          "vtv",
          "patente",
          "autopista",
          "avión",
          "moto",
          "bicicleta",
        ],
      },
      {
        category: "Entretenimiento",
        keywords: [
          "cine",
          "streaming",
          "netflix",
          "spotify",
          "bar",
          "boliche",
          "previa",
          "salida",
          "teatro",
          "recital",
          "concierto",
          "show",
          "festival",
          "museo",
          "disney",
          "youtube",
          "twitch",
          "steam",
          "playstation",
          "xbox",
          "nintendo",
          "videojuego",
          "pub",
          "bowling",
          "karaoke",
          "fiesta",
          "cancha",
          "fútbol",
        ],
      },
      {
        category: "Servicios",
        keywords: [
          "luz",
          "gas",
          "agua",
          "internet",
          "celular",
          "cable",
          "edenor",
          "edesur",
          "metrogas",
          "aysa",
          "telecom",
          "movistar",
          "fibertel",
          "flow",
          "telecentro",
          "directv",
          "abl",
          "arba",
          "afip",
          "monotributo",
          "impuesto",
          "wifi",
          "teléfono",
        ],
      },
      {
        category: "Salud",
        keywords: [
          "farmacia",
          "médico",
          "doctor",
          "obra social",
          "gimnasio",
          "dentista",
          "oculista",
          "prepaga",
          "osde",
          "swiss",
          "galeno",
          "medicus",
          "hospital",
          "clínica",
          "sanatorio",
          "laboratorio",
          "análisis",
          "radiografía",
          "vacuna",
          "kinesiólogo",
          "psicólogo",
          "psiquiatra",
          "nutricionista",
          "pediatra",
          "ginecólogo",
          "cardiólogo",
          "traumatólogo",
          "dermatólogo",
          "terapia",
          "remedio",
          "medicamento",
          "pastilla",
          "gym",
          "pilates",
          "yoga",
          "natación",
          "pádel",
          "masaje",
          "óptica",
          "anteojos",
          "lente",
          "ortodoncia",
        ],
      },
      {
        category: "Alquiler",
        keywords: ["alquiler", "expensas", "renta", "inmobiliaria"],
      },
      {
        category: "Indumentaria",
        keywords: [
          "ropa",
          "indumentaria",
          "remera",
          "pantalón",
          "jean",
          "campera",
          "buzo",
          "camisa",
          "vestido",
          "pollera",
          "abrigo",
          "zapatilla",
          "zapato",
          "calzado",
        ],
      },
      {
        category: "Hogar",
        keywords: [
          "ferretería",
          "bazar",
          "mueble",
          "colchón",
          "sommier",
          "sábana",
          "toalla",
          "almohada",
          "cortina",
          "vajilla",
          "olla",
          "sartén",
          "detergente",
          "lavandina",
          "jabón",
          "escoba",
          "trapo",
          "limpieza",
          "lamparita",
          "enchufe",
          "herramienta",
        ],
      },
      {
        category: "Cuidado personal",
        keywords: [
          "peluquería",
          "peluquero",
          "barbería",
          "barbero",
          "manicura",
          "pedicura",
          "depilación",
          "tintura",
          "perfumería",
          "perfume",
          "shampoo",
          "champú",
          "desodorante",
          "maquillaje",
          "cosmética",
          "spa",
        ],
      },
      {
        category: "Mascotas",
        keywords: [
          "veterinaria",
          "veterinario",
          "mascota",
          "perro",
          "gato",
          "balanceado",
          "cucha",
          "antipulgas",
          "pipeta",
        ],
      },
    ]);
  });
});
