/**
 * The 258 keyword table (kb.md "Categorización Automática", RF-06), the
 * single normative source of category order and per-category keywords.
 *
 * Transcribed from kb.md exactly as written -- category order, and the
 * keywords within each category, are NOT reordered, added to, or removed
 * from here. Reordering this list, or moving a keyword between categories,
 * silently changes classifications that already work (AGENTS.md, kb.md
 * rule 4 of "Reglas de coincidencia").
 *
 * Deliberately an explicit typed array, not an object keyed by category
 * name: the normative order must be structurally visible in the type. An
 * object literal relies on JS's implicit insertion-order guarantee, which
 * an ESLint `sort-keys` autofix -- or a "let me tidy this alphabetically"
 * refactor -- breaks with no compiler error and a changed classification
 * (mitigation R-04, PLAN audit finding).
 *
 * Keywords are stored here exactly as written in kb.md, with their original
 * accents. `pluralize.ts` normalizes them before deriving match forms,
 * because matching itself always happens against normalized input tokens.
 */

export interface CategoryKeywords {
  category: string;
  keywords: string[];
}

export const CATEGORY_KEYWORDS: readonly CategoryKeywords[] = [
  {
    category: "Comida",
    keywords: [
      "supermercado",
      "super",
      "almacén",
      "restaurante",
      "delivery",
      "kiosco",
      "verdulería",
      "panadería",
      "desayuno",
      "almuerzo",
      "merienda",
      "cena",
      "vianda",
      "picada",
      "café",
      "cafetería",
      "milanesa",
      "empanada",
      "pizza",
      "hamburguesa",
      "asado",
      "choripán",
      "pancho",
      "sándwich",
      "sanguche",
      "sushi",
      "tarta",
      "ensalada",
      "medialuna",
      "pan",
      "helado",
      "alfajor",
      "galletita",
      "chocolate",
      "yerba",
      "gaseosa",
      "fiambre",
      "queso",
      "leche",
      "huevo",
      "carne",
      "pollo",
      "pescado",
      "verdura",
      "fruta",
      "fideo",
      "arroz",
      "rotisería",
      "carnicería",
      "pescadería",
      "fiambrería",
      "heladería",
      "pizzería",
      "parrilla",
      "dietética",
      "comedor",
      "mayorista",
      "chino",
      "rappi",
      "pedidosya",
      "mcdonalds",
      "coto",
      "carrefour",
      "jumbo",
      "changomas",
      "makro",
    ],
  },
  {
    category: "Transporte",
    keywords: [
      "nafta",
      "combustible",
      "colectivo",
      "subte",
      "tren",
      "taxi",
      "remis",
      "uber",
      "cabify",
      "peaje",
      "estacionamiento",
      "gnc",
      "gasoil",
      "ypf",
      "shell",
      "axion",
      "bondi",
      "sube",
      "micro",
      "combi",
      "pasaje",
      "boleto",
      "didi",
      "cochera",
      "garaje",
      "gomería",
      "lavadero",
      "mecánico",
      "taller",
      "vtv",
      "patente",
      "autopista",
      "avión",
      "moto",
      "bicicleta",
    ],
  },
  {
    category: "Entretenimiento",
    keywords: [
      "cine",
      "streaming",
      "netflix",
      "spotify",
      "bar",
      "boliche",
      "previa",
      "salida",
      "teatro",
      "recital",
      "concierto",
      "show",
      "festival",
      "museo",
      "disney",
      "youtube",
      "twitch",
      "steam",
      "playstation",
      "xbox",
      "nintendo",
      "videojuego",
      "pub",
      "bowling",
      "karaoke",
      "fiesta",
      "cancha",
      "fútbol",
    ],
  },
  {
    category: "Servicios",
    keywords: [
      "luz",
      "gas",
      "agua",
      "internet",
      "celular",
      "cable",
      "edenor",
      "edesur",
      "metrogas",
      "aysa",
      "telecom",
      "movistar",
      "fibertel",
      "flow",
      "telecentro",
      "directv",
      "abl",
      "arba",
      "afip",
      "monotributo",
      "impuesto",
      "wifi",
      "teléfono",
    ],
  },
  {
    category: "Salud",
    keywords: [
      "farmacia",
      "médico",
      "doctor",
      "obra social",
      "gimnasio",
      "dentista",
      "oculista",
      "prepaga",
      "osde",
      "swiss",
      "galeno",
      "medicus",
      "hospital",
      "clínica",
      "sanatorio",
      "laboratorio",
      "análisis",
      "radiografía",
      "vacuna",
      "kinesiólogo",
      "psicólogo",
      "psiquiatra",
      "nutricionista",
      "pediatra",
      "ginecólogo",
      "cardiólogo",
      "traumatólogo",
      "dermatólogo",
      "terapia",
      "remedio",
      "medicamento",
      "pastilla",
      "gym",
      "pilates",
      "yoga",
      "natación",
      "pádel",
      "masaje",
      "óptica",
      "anteojos",
      "lente",
      "ortodoncia",
    ],
  },
  {
    category: "Alquiler",
    keywords: ["alquiler", "expensas", "renta", "inmobiliaria"],
  },
  {
    category: "Indumentaria",
    keywords: [
      "ropa",
      "indumentaria",
      "remera",
      "pantalón",
      "jean",
      "campera",
      "buzo",
      "camisa",
      "vestido",
      "pollera",
      "abrigo",
      "zapatilla",
      "zapato",
      "calzado",
    ],
  },
  {
    category: "Hogar",
    keywords: [
      "ferretería",
      "bazar",
      "mueble",
      "colchón",
      "sommier",
      "sábana",
      "toalla",
      "almohada",
      "cortina",
      "vajilla",
      "olla",
      "sartén",
      "detergente",
      "lavandina",
      "jabón",
      "escoba",
      "trapo",
      "limpieza",
      "lamparita",
      "enchufe",
      "herramienta",
    ],
  },
  {
    category: "Cuidado personal",
    keywords: [
      "peluquería",
      "peluquero",
      "barbería",
      "barbero",
      "manicura",
      "pedicura",
      "depilación",
      "tintura",
      "perfumería",
      "perfume",
      "shampoo",
      "champú",
      "desodorante",
      "maquillaje",
      "cosmética",
      "spa",
    ],
  },
  {
    category: "Mascotas",
    keywords: [
      "veterinaria",
      "veterinario",
      "mascota",
      "perro",
      "gato",
      "balanceado",
      "cucha",
      "antipulgas",
      "pipeta",
    ],
  },
];
